### ISSUE TITLE
Product Goals and Priorities

### ISSUE THREAD

**Issue by claire-kz** [Alastair-Cleve/CommonCents#1]
- What do "Links to competitor website via query string"  and "Interactive breadcrumbs throughout transfer process" mean?  Clarify these bullet point. 
- Make the following P2s into P3s: User reviews side-scrolling carousel, Graph of exchange rates over past 30 days (checkout D3.js for this!).  These are both great features, but will probably be time-intensive.      
- Currency conversion widget: which currencies do you want to support in the MVP?  Will the exchange rates be fixed or pulled from an API?
- Great detail!

**Comment by Alastair-Cleve** [comment]
Claire,

Thank you for taking the time to review my proposal. I really value your feedback, as I am still trying to grapple with the scope of my project. Let me try to take your bullet points in order:
1. "Links to competitor website": if you scroll down to the 30-day trend graph on TransferWise.com, you will see a link to xe.com, which shows the same 30-day trend (the point is to show how TransferWise's rates are the same as the actual mid-market rates). Linking to xe.com looks surprisingly easy; for example, here is the link to the USD:GBP rate: http://www.xe.com/currencycharts/?from=USD&to=GBP&view=1M. Basically, I can create this link for any pair of currencies by changing everything after the ?. So, USD:EUR should be ?from=USD&to=EUR&view=1M.
2. "Interactive breadcrumbs": what I meant by this is that while a user completes the transfer process, there will be a list of numbers that shows where the user is that expand when the user is at that stage. For example, suppose there is a five-step process for making a purchase on amazon: when the user is on step 2, number 1 and numbers 3-5 shrink, whereas number 2 expands. Basically, the idea is to give the use a sense of "place" in the transfer process.
3. I want to support all of the currencies that are provided by api.fixer.io, which is an API for current and historical FOREX rates published by the ECB. I don't want to list all of them here (there are about 20), but if you paste this into your browser, you can see the JSON output: https://api.fixer.io/latest.

It's pretty nice.
1. Thank you for giving me a more realistic time expectation of the scrolling carousel and exchange-rate graph.  

-Alastair
