### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by claire-kz** [Alastair-Cleve/CommonCents#2]
- Great job!
- Make sure to have an overall parent container on the landing page.  I think the components you have make sense for `<section>` containers, but will they will need sub-elements for things like the conversion or graph widgets.  Having larger containers that the functional components sit in will make organizing the page much easier.  
- Love the transfer and dashboard, but they look quite challenging.  Consider having an MVP version.

**Comment by Alastair-Cleve** [comment]
I agree that the <section> tag is the way to go. I've updated my ReadMe to reflect what we discussed yesterday. The MVP roadmap is: (1) Login, (2) Conversion Widget, (3) Transfer Page, (4) Navbar, and (5) Dashboard.
