### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by claire-kz** [Alastair-Cleve/CommonCents#4]
- What is savings?  Is this the amount that people have in their account?  Why does it have a latitude and longitude?
- Transfers - don't need date made column, use rails timestamps.  Transferee should be an indexed foreign key pointing to the users table.

**Comment by Alastair-Cleve** [comment]
I mentioned this yesterday, but I think it's worth repeating. Savings is intended for the map showing the amount that people saved on recent transactions. But this has been demoted to a stretch goal; consequently, we can address the database logic when we get there.

I've eliminated the date made column in my schema, changed user_id to transferor, and added transferee. This is reflected in my schema.md.
