### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by claire-kz** [Alastair-Cleve/CommonCents#5]
- Frontend or backend auth?  If frontend, allow more time for this phase.
- I recommend leaving 2 days for phase 2 and making phase 3 a stretch goal.  
- Phases 4 & 5 should be stretch goals - not crucial functionality for MVP
- Phases 7 & 8 each need at least 2 days.  I think these components will be very time-intensive - consider breaking up into more steps.

**Comment by Alastair-Cleve** [comment]
I'll be using front-end authentication, so I'll be consulting day 2 of the BenchBnB solution. Meanwhile, I've completely re-organized my timeline, which should now be reflected on GitHub.
