### ISSUE TITLE
Repo Organization

### ISSUE THREAD

**Issue by claire-kz** [Alastair-Cleve/CommonCents#6]
Root folder of repo should be project.  Make the CommonCents repo readme the readme for the project itself, and save any supporting files in the project's docs folder.

**Comment by Alastair-Cleve** [comment]
I've made these changes. Hopefully, I didn't accidentally move a file into the wrong folder.

**Comment by Alastair-Cleve** [comment]
I think the filesystem is in good shape. I initialized a throw-away rails project in order to compare the file structure to the file structure in my CommonCents project, and everything seemed to be in the right place.
